server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alley_v2?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xiayi
    password:

oss:
  bucket-name:
  end-point:
  accesskey-id:
  accesskey-secret:
  dir:
  callback:
  max_size: 10

wechat:
  app-id:
  app-secret:

logging:
  file:
    name: src/main/resources/logs/log